Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    with open(output_path_country,'w') as f:
NameError: name 'output_path_country' is not defined
Traceback (most recent call last):
  File "src/map.py", line 93, in <module>
    f.write(json.dumps(counter_lang))
NameError: name 'output_path_country' is not defined
